package com.mycompany.ticket_manager.view;

import com.mycompany.ticket_manager.controller.StaffController;
import com.mycompany.ticket_manager.model.CurrentStaff;
import com.mycompany.ticket_manager.model.Login;
import com.mycompany.ticket_manager.model.Response;
import com.mycompany.ticket_manager.view.admin.FrameAddStaff;
import com.mycompany.ticket_manager.view.staff.readQr;
import com.mycompany.ticket_manager.view.admin.Main;
import com.mycompany.ticket_manager.view.staff.BuyTicket;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class FrameLogin extends javax.swing.JFrame {

    StaffController staffController;
    private JPanel contentPanel;

    public FrameLogin() {
        setTitle("Frame A");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);
        initComponents();
        this.setDefault();
        this.staffController = new StaffController();
    }

    private void setDefault() {
        this.email.setText("abc@gmail.com");
        this.password.setText("staff");
//        this.email.setText("chienboy03@gmail.com");
//        this.password.setText("admin");
        this.error.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        login_admin = new javax.swing.JButton();
        login_staff = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        openFrameAddStaffActionPerformed = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("login"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");

        jLabel2.setText("Email");

        jLabel3.setText("Mật khẩu");

        login_admin.setText("Đăng nhập với admin");
        login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickLoginAdmin(evt);
            }
        });

        login_staff.setText("Đăng nhập với khách hàng");
        login_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickLoginStaffBuyTicket(evt);
            }
        });

        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setText("err");

        openFrameAddStaffActionPerformed.setText("Đăng ký");
        openFrameAddStaffActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFrameAddStaffActionPerformedActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ảnh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openFrameAddStaffActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login_staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email)
                            .addComponent(password)
                            .addComponent(login_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addComponent(error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_staff)
                .addGap(18, 18, 18)
                .addComponent(openFrameAddStaffActionPerformed)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setError(String error) {
        this.error.setText(error);
    }

    private void cleanError() {
        this.error.setText("");
    }

    private Login getInfoLogin() {
        String email = this.email.getText();
        String password = new String(this.password.getPassword());
        return new Login(email, password);
    }
    private void clickLoginAdmin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickLoginAdmin
        // TODO add your handling code here:
        Login infoLogin = this.getInfoLogin();
        Response response = this.staffController.login(infoLogin.getEmail(), infoLogin.getPassword(), "admin");
        if (response.getSuccess() == false) {
            this.error.setText(response.getMessage());
            return;
        }

        Main mainAdmin = new Main();
        mainAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clickLoginAdmin

    private void clickLoginStaffBuyTicket(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickLoginStaffBuyTicket
        // TODO add your handling code here:
        Login infoLogin = this.getInfoLogin();
        Response<CurrentStaff> response = this.staffController.login(infoLogin.getEmail(), infoLogin.getPassword(), "staff");
        if (response.getSuccess() == false) {
            this.error.setText(response.getMessage());
            return;
        }

        BuyTicket mainBuy = new BuyTicket(response.getData());
        mainBuy.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clickLoginStaffBuyTicket

    private void openFrameAddStaffActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFrameAddStaffActionPerformedActionPerformed

        JFrame frame = new JFrame("Đăng kí tài khoản người dùng");
        FrameAddStaff addStaffPanel = new FrameAddStaff(); // Tạo JPanel

        // Thêm JPanel vào JFrame
        frame.add(addStaffPanel);
        frame.setSize(790, 390); // Đặt kích thước cho JFrame
        frame.setLocationRelativeTo(null); // Hiển thị ở giữa màn hình
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Đóng frame này khi nhấn nút close
        frame.setVisible(true); // Hiển thị JFrame

    }//GEN-LAST:event_openFrameAddStaffActionPerformedActionPerformed
    private void addPanelToFrame(JPanel panel) {
        panel.setBounds(10, 10, 200, 200); // Đặt vị trí và kích thước cho panel
        panel.setBackground(new java.awt.Color(200, 200, 255)); // Đặt màu nền cho panel (tuỳ chỉnh)
        this.getContentPane().add(panel); // Thêm panel vào giao diện của FrameLogin
        this.revalidate(); // Cập nhật lại giao diện
        this.repaint();    // Vẽ lại frame
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login_admin;
    private javax.swing.JButton login_staff;
    private javax.swing.JButton openFrameAddStaffActionPerformed;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
